sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '12'
  - '10'
  - stable
after_success:
  - npm run semantic-release
env:
  global:
    - secure: XXQWV+c3Axb+G3WtYt1Z2wjv1EVSny91D7DVMSgtKnd7TtxsPzfpy7iWPFxidxi4vFLbi35JC51BZ7BWnN1tmgiGbZtk6NkgG3amNyVE4RSvPAMOO5wCEe2SqXU+59aW+1s/kRGbuy5fA6pTL+OpGjVq0FIa0GmPxNSI13AEKs7pW8ijWdkM7MtY1q/Hw1HjIvZno4iW8gVkhznOlgw08iW2fk2l5dS/OMDXZgrn+OwfbZ1sIDdqF3RTnLoxngLuk8UvHMT9W0xiU/8O01HOXE9rp71hV/NYYiJk9Ghg4x/6ss9bt08p8s2MvM8QGNbVfyawPwEwSVvEfH8OdFm48btPmziFp/4HSINrgi2bUEziAvgttTX1K8TXI/P7DlvmKJLOoaprCfeicGSN/Q0vuIPQkVl2dziV7pk/BiVbjMpB8BQIZD2VJFrRvylzLDbrcy7gIcSn50nHpYqKevr6tnJ9VmioHeNbYwloYD+uBx0mby/I68Ii4y51gPKIYQ1lza4KtEIpjs3Vs4RrIuKTjd+0Fb6vXJL/uzjeokd3TDyVKi1AGRzS9RMccZUS5EaGHfOy19nMfWuL1snZ7GKIJZy7gI5IH3KpYV14YHw8hx0ExZmlWZmavGJPRsXN/ervfX3do7Alj7+KakkV8ip9KkJqxwPajXH80cJrfEncODY=
    - secure: yL3tp23cSwaHhrE7XzdOhrBpzyQgFpcT2b5CmFOoLaMOoIKd6Bq9rTd8un5egbFfTjivGEPx2+EfZs6qL0d496HomvGIWeLmNp+GZGL1ynCtrw8fDSQqNH7uguSlYsIAfNuV1x7N/9172rLLiNuIXB2/GNoLPJ4WbUJo/7aT5NE2MJvqYk7jWglkTtTYLoGhAd4aHVMfavC8hHqueXHFQ4VscvfDciaqwN+SfB35+tnTB4NMpslypmfd5c6bz3XHRVb8qKi3jgNe13ftcvbFkn6F3JO6gNI9omyESCGcjYIGzjPw5oKuYD4SAiEbiqIBwclU/oymFfTLBWE3Nq+pXjyUViTe6fV6mF1k+44OOg5XCCZPt6Q/JLQcK5TfQw2AkZkiUU6bQ/G43uhI+WZ1su4ka+eOGbLRv4D/rmZLv25ZVNlwVWb/8B/YmQqhX35Oi8m1M8Uq1QjpF+w2H13gRFa9R9qh0T82LnVIq6HBkIl2eBftHL1yL58bZ+D20tHRRm8soof8o3SuPXyILjcbKWyOrgO6TG+nwe6qLIWVGXW1Vkc1F8RiYsKeuI+wBenAqm8QReCO2lFqRArKze6XlKva8c+uB7rzHSYKj7tw96iu4yP9XRLL38kPMHgTEg94r+vyoMJCt8jwwfg52scC8HWl+yxwMnq1ZYdoSPT5UZA=
